drivers: stm32_risaf: fix build error on unused argument
Fixes a build error due to an unused variable when building with
trace message disabled.

core/drivers/firewall/stm32_risaf.c:269:68: error: unused parameter ‘risaf’ [-Werror=unused-parameter]
  269 | static TEE_Result risaf_check_overlap(struct stm32_risaf_instance *risaf,
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

Change-Id: I4cd485c0e4d37c6c5066bf323df3feca331020be
Signed-off-by: Etienne Carriere <etienne.carriere@foss.st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/323294
Domain-Review: Yann GAUTIER <yann.gautier@foss.st.com>