plat-stm32mp1: fix missing __unused attribute in tamper handlers
Adds missing __maybe_unused attribute to variable in platform functions
stm32mp1_itamper_action() and stm32mp1_etamper_action(). This fixes
build warnings/errors reported by compiler when OP-TEE is built with
CFG_TEE_CORE_LOG_LEVEL=0, as in trace message below:

core/arch/arm/plat-stm32mp1/main.c: In function ‘stm32mp1_itamper_action’:
core/arch/arm/plat-stm32mp1/main.c:706:21: error: variable ‘tamp_name’ set but not used [-Werror=unused-but-set-variable]
  706 |         const char *tamp_name = NULL;
      |                     ^~~~~~~~~
core/arch/arm/plat-stm32mp1/main.c: In function ‘stm32mp1_etamper_action’:
core/arch/arm/plat-stm32mp1/main.c:717:54: error: unused parameter ‘id’ [-Werror=unused-parameter]
  717 | static uint32_t __unused stm32mp1_etamper_action(int id)
      |                                                  ~~~~^~

Change-Id: I31047f026ec012ba75957696346db44d2c0c3197
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/294202
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
Tested-by: Etienne CARRIERE <etienne.carriere@foss.st.com>
Reviewed-by: Etienne CARRIERE <etienne.carriere@foss.st.com>
Reviewed-by: Gatien CHEVALLIER <gatien.chevallier@st.com>
Domain-Review: Lionel DEBIEVE <lionel.debieve@foss.st.com>